test:
  mode: test
  login: 4Bf3vt6KL7
  key: 484MR5s7vW5uY8p2

development:
  mode: test
  login: 4Bf3vt6KL7
  key: 484MR5s7vW5uY8p2

production:
  mode: test
  login: 4Bf3vt6KL7
  key: 484MR5s7vW5uY8p2

actual_production:
  mode: production
  login: nil
  key: nil